version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - java -version
      - echo "Installing Maven..."
      - mvn --version
  build:
    commands:
      - echo "Building the Spring Boot application..."
      - mvn clean install -DskipTests=true
  post_build:
    commands:
      - mv target/monitoramento-0.0.1-SNAPSHOT.jar monitoramento-0.0.1-SNAPSHOT.jar

artifacts:
  files:
    - monitoramento-0.0.1-SNAPSHOT.jar
