version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - java -version
      - echo "Installing Maven..."
      - mvn --version
  build:
    commands:
      - echo "Building the Spring Boot application..."
      - mvn clean install -DskipTests=true
  post_build:
    commands:
      - mv target/moitoramento-0.0.1-SNAPSHOT.jar moitoramento-0.0.1-SNAPSHOT.jar

artifacts:
  files:
    - moitoramento-0.0.1-SNAPSHOT.jar
    - .ebextensions/*

cache:
  paths:
    - '/root/.m2/**/*'
