version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - java -version
      - echo "Installing Maven..."
      - mvn --version
  build:
    commands:
      - echo "Building the Spring Boot application..."
      - mvn clean install -DskipTests=true
  post_build:
    commands:
      - echo "Deploying to Elastic Beanstalk..."
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - eb init -r $AWS_REGION -p "java" $BEANSTALK_APP_NAME
      - eb use $BEANSTALK_ENV_NAME
      - eb deploy

artifacts:
  files: target/*

cache:
  paths:
    - '/root/.m2/**/*'
